<Project>
  <ItemGroup>
    <PackageVersion Include="BouncyCastle.Cryptography" Version="2.7.0" />
    <PackageVersion Include="Duende.IdentityModel" Version="8.1.0" />
    <PackageVersion Include="Duende.IdentityModel.OidcClient" Version="7.1.0" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.12" />
    <PackageVersion Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
  </ItemGroup>
</Project>
