<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <LangVersion>11</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle" />
    <PackageReference Include="HelseId.Constants" />
    <PackageReference Include="IdentityModel" />
    <PackageReference Include="IdentityModel.OidcClient" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="System.Net.Http" />
    <PackageReference Include="System.Security.Cryptography.Cng" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelseId.Models\HelseId.Models.csproj" />
  </ItemGroup>

</Project>
